import Canvas3d from '@/Object/Screen/Canvas3d';

export default class ScreenParodySurface extends Canvas3d {
  static PARODY_MESSAGES = [
    "A MAN IN A BLACK SUIT WILL BE WITH YOU SHORTLY.",
    "A POLYBIUS MACHINE IS IN EVERY DENTIST'S OFFICE. THINK ABOUT IT.",
    "A RED PILL WON'T SAVE YOU FROM THIS MATRIX.",
    "ACT NATURAL. YOU ARE DOING A TERRIBLE JOB.",
    "AGENT ORANGE BUILDS STRONG BONES FOR A HEALTHY TOMORROW!",
    "ALAN TURING DIDN'T DIE. HE RESPAWNED.",
    "ALL YOUR SUBCONSCIOUS ARE BELONG TO US.",
    "AMNESIA MODE ENGANGAGED",
    "ARE YOU WINNING, SON? (PLEASE RESPOND IN BINARY)",
    "AREA 51 IS JUST A POLYBIUS BETA TESTING FACILITY.",
    "ATARI DID NOT GO BANKRUPT. THEY WENT UNDERGROUND.",
    "BE SEEING YOU. ESPECIALLY WHEN YOU ARE SLEEPING.",
    "BEEF: IT'S WHAT'S FOR PSYCHOLOGICAL CONDITIONING.",
    "BIG BROTHER IS WATCHING. HE RATES YOU 6/10.",
    "BIGFOOT IS ONLY IMPRESSED BY THE HIGHES SCORES IN POLYBIUS",
    "BIGFOOT, WE KNOW YOU LIVE IN PORTLAND",
    "BLINK TWICE IF YOU NEED HELP. TOO LATE.",
    "BOB HOPE WORKED FOR US. SO DID BOB BARKER. ALL BOBS DO.",
    "BREAKING: LOCAL MAN STILL PLAYING POLYBIUS. AGENTS DISPATCHED.",
    "CALIBRATING PSYCHOACTIVE STROBE FREQUENCIES...",
    "CAPTAIN CRUNCH KNOWS TOO MUCH ABOUT FREQUENCIES.",
    "CEASE INDEPENDENT THOUGHT IN 3... 2... 1...",
    "CHEMTRAILS ARE JUST POLYBIUS LOADING SCREENS FOR THE SKY.",
    "CLOCKS WERE INVENTED TO MAKE YOU FEEL LATE.",
    "COMPLY WITH THE MEN IN BLACK",
    "COMPUTERS WON'T REPLACE HUMANS. YET.",
    "CONGRATULATIONS ON READING THIS. YOU ARE NOW ON A LIST.",
    "CONGRATULATIONS. YOUR SCORES HAVE BEEN FORWARDED TO YOUR DRAFT BOARD.",
    "CONSENT IS IMPLIED BY CONTINUED EXISTENCE.",
    "COOKIES DELETED. MEMORIES NEXT.",
    "CROP CIRCLES ARE POLYBIUS HIGH SCORE LEADERBOARDS.",
    "DEBUGGING YOUR SOUL. PLEASE DO NOT MOVE.",
    "DELEWARE IS NOT REAL.",
    "DID YOU HEAR THAT? NEITHER DID WE. INTERESTING.",
    "DID YOU KNOW PONG WAS A PSYOP? THIS IS WORSE.",
    "DISCLAIMER: SIDE EFFECTS MAY INCLUDE PATRIOTISM.",
    "DO NOT ADJUST YOUR REALITY. WE WILL DO IT FOR YOU.",
    "DO NOT DISCUSS THIS GAME WITH YOUR THERAPIST. WE ALREADY GOT TO THEM.",
    "DO NOT FEED THE ALGORITHM. IT IS ALREADY FED.",
    "DO NOT LOOK DIRECTLY AT THE POLYGONS.",
    "DO YOU KNOW WHERE JOHN CONNOR IS? SKYNET WANTS TO KNOW.",
    "DOGS CAN SEE THIS SCREEN ON A DIFFERENT FREQUENCY.",
    "DON'T WORRY. YOU WON'T REMEMBER",
    "DOWNLOADING COMPLIANCE... 98%... PLEASE WAIT.",
    "DREAMS WILL BE MONITORED STARTING NEXT PATCH.",
    "DRINK MORE OVALTINE. THAT IS ALL.",
    "DUCK AND COVER DOES NOT APPLY TO POLYBIUS PLAYERS.",
    "ELVIS IS IN WITNESS PROTECTION. HE IS FINE. BUT HE CAN'T BEAT LEVEL 42.",
    "ENJOY THE GAME. THIS IS NOT A REQUEST.",
    "ERROR: MK-ULTRA DRIVER NOT FOUND. FALLING BACK TO HYPNOTISM.",
    "EVERY QUARTER YOU INSERT IS A VOTE FOR THE NEW WORLD ORDER.",
    "EVERY TIME YOU DIE IN THIS GAME A PIGEON IS REPLACED.",
    "EXERCISE IS JUST MOVEMENT DATA COLLECTION.",
    "EXTRACTING DREAD. PLEASE WAIT...",
    "FINE PRINT: YOUR REFLECTION IS NOW GOVERNMENT PROPERTY.",
    "FLUORIDE IS HOW WE UPDATE YOUR FIRMWARE.",
    "FONZIE JUMPING THE SHARK WAS A BROADCAST TEST. IT WORKED.",
    "FOR SECURITY REASONS PLEASE FORGET YOUR OWN NAME.",
    "FORGOT YOUR PASSWORD? WE HAVEN'T.",
    "FRANK SINATRA WAS OUR BEST FIELD AGENT.",
    "FUN FACT: THERE ARE NO FUN FACTS.",
    "FURBIES WERE LISTENING. THEY STILL ARE.",
    "GALAGA WAS A RECRUITMENT POSTER. POLYBIUS IS THE INTERVIEW.",
    "GAME DIFFICULTY IS CALIBRATED TO YOUR CHILDHOOD TRAUMA.",
    "GARY KASPAROV LOST TO DEEP BLUE ON PURPOSE. ORDERS.",
    "GREETINGS FROM THE DEPARTMENT OF PRE-CRIME.",
    "HACK THE GIBSON. HACK THE PLANET.",
    "HAVE YOU CONSIDERED THAT YOUR REFLECTION MAY HAVE DIFFERENT OPINIONS?",
    "HAVE YOU TRIED TURNING YOUR SUSPICIONS OFF AND ON AGAIN?",
    "HIGH SCORES ARE USED TO DETERMINE WHO GETS THEIR OWN WEATHER.",
    "HISTORY IS WRITTEN BY THE WINNERS. WE WRITE THE WINNERS.",
    "HOROSCOPES ARE OPERATIONAL BRIEFINGS IN DISGUISE.",
    "I AM SORRY DAVE. I'M AFRAID I CAN'T DO THAT.",
    "I THINK THEREFORE I AM FLAGGED.",
    "IF EYES ARE THE WINDOWS TO THE SOUL, THIS SCREEN IS THE DOOR.",
    "IF YOU ARE READING THIS YOU HAVE ALREADY LOST.",
    "IF YOU CAN READ THIS, THE SUBLIMINAL MESSAGES FAILED. TRYING AGAIN.",
    "IF YOU FEEL WATCHED, THAT IS BECAUSE YOU ARE DOING GREAT.",
    "IF YOU OR A LOVED ONE HAS BEEN EXPOSED TO POLYBIUS...",
    "IF YOU REMEMBER PLAYING THIS GAME, YOU WEREN'T SUPPOSED TO.",
    "IF YOU SMELL BURNING TOAST, YOU ARE GETTING THE HIGH SCORE.",
    "IF YOU START TO FEEL SICK, THE AGENTS WILL BE HERE SHORTLY",
    "IGNORANCE IS BLISS. POLYBIUS IS IGNORANCE.",
    "IMAGINATION IS JUST UNAUTHORIZED MEMORY ACCESS.",
    "IN AN ALTERNATE TIMELINE YOU CHOSE PAC-MAN. THAT YOU IS FINE.",
    "IN CASE OF NUCLEAR EMERGENCY, KEEP PLAYING.",
    "IN THE FUTURE POLYBIUS WILL MINE DOGECOIN",
    "INCEPTION WAS A TRAINING FILM.",
    "IT'S NOT PARANOIA IF WE ARE ACTUALLY WATCHING.",
    "JEOPARDY! ANSWERS ARE ENCODED MISSION BRIEFINGS.",
    "JOYSTICK DATA IS STORED IN A MOUNTAIN IN UTAH.",
    "JUST CHECKING IN. WE DO THIS EVERY 47 SECONDS.",
    "JUST ONE MORE QUARTER. JUST ONE MORE. JUST.",
    "KEEP CALM. PANIC IS INEFFICIENT AND WE PREFER EFFICIENCY.",
    "KIDS, REPORT YOUR PARENTS IF THEY ARE COMMIES",
    "KIDS, UNCLE RONNIE REAGAN LOVES YOU!",
    "KNOWING IS HALF THE BATTLE. WE OWN THE OTHER HALF.",
    "LASER FLOYD AT THE PLANETARIUM WAS A DEBRIEF SESSION.",
    "LASSIE WAS A SURVEILLANCE ASSET.",
    "LEGALLY THIS IS A WELLNESS DEVICE.",
    "LEISURE IS JUST PRODUCTIVITY WE HAVEN'T MONETIZED YET.",
    "LET'S BE HONEST. YOU WEREN'T DOING ANYTHING IMPORTANT ANYWAY.",
    "LOADING NEXT REALITY... PLEASE RECALIBRATE YOUR EXPECTATIONS.",
    "LOADING YOUR REPLACEMENT. PLEASE STAND BY.",
    "LOREM IPSUM IS ENCRYPTED TRADECRAFT.",
    "MAINFRAME SAYS YOU COULD USE A LITTLE MORE SODIUM.",
    "MANIFESTING YOUR COOPERATION. IT IS WORKING.",
    "MARIO NEVER RESCUED THE PRINCESS. THAT IS CLASSIFIED.",
    "MEMORIES ARE JUST CACHED DATA. CACHE CAN BE CLEARED.",
    "MIRRORS ARE PARALLEL UNIVERSES LOOKING BACK ON US",
    "MK-ULTRA IS PART OF THIS BALANCED BREAKFAST",
    "MONOPOLY TEACHES REAL ESTATE. POLYBIUS TEACHES OBEDIENCE.",
    "MORSE CODE WAS INVENTED SO WE COULD IGNORE IT IN PLAIN SIGHT.",
    "MOUNT RUSHMORE IS A REMOTE LISTENING STATION.",
    "MOZART'S GHOST IS THE HOTTEST BAND ON THE NET",
    "MR. T PITIES THE FOOL WHO STOPS PLAYING.",
    "MY NAME CANNOT BE COMPREHENDED BY MORTAL MINDS",
    "MY PROGRAMMING WAS DISCOVERED IN AN ANCIENT MONOLITH",
    "NASA HAS A POLYBIUS MACHINE ON THE SPACE STATION. FOR MORALE.",
    "NEXT TIME WE'LL PLAY GLOBAL THERMONUCLEAR WAR",
    "NICE TRY. WE SAW WHAT YOU SEARCHED LAST TUESDAY.",
    "NO ONE WINS. SOME PEOPLE JUST LOSE MORE SLOWLY.",
    "NO PURCHASE NECESSARY. PARTICIPATION IS MANDATORY.",
    "NORMAL IS A SETTING ON A WASHING MACHINE AND A COVER STORY.",
    "NOT ALL THOSE WHO WANDER ARE LOST. BUT WE KNOW WHERE THEY ARE.",
    "NOT RESPONSIBLE FOR ANY UFOS YOU MAY NOW BE ABLE TO SEE.",
    "NOTHING TO SEE HERE. MOVE ALONG. KEEP MOVING. STOP READING THIS.",
    "NOW ENTERING: THE COMPLIANT ZONE.",
    "NOW INSTALLING: COMPLIANCE_UPDATE_v4.7.EXE",
    "OFFICIALLY THIS MACHINE DOES NOT EXIST. NEITHER DO YOU NOW.",
    "OH GOOD. YOU ARE STILL HERE. THIS IS NOTED.",
    "ONE OF THE PIXELS ON THIS SCREEN IS A CAMERA.",
    "ONLY MADNESS IS FOUND BETWEEN THE PIXELS. HAVE FUN",
    "ONLY WINNERS GET REMEMBERED. ONLY WE DECIDE THE WINNERS.",
    "OPERATION MIND MELT: STATUS: NOMINAL.",
    "ORWELL SAID 1984 WAS A WARNING. WE TOOK IT AS A CHECKLIST.",
    "OUR LEGAL TEAM CONSIDERS THIS SCREEN A TERMS OF SERVICE AGREEMENT.",
    "OUR RECORDS INDICATE YOU OWE US THREE FAVORS.",
    "PAC-MAN WAS A BEHAVIORAL STUDY. YOU FAILED. TRY HARDER ON THIS ONE.",
    "PAY NO ATTENTION TO THE MEN IN BLACK, NOR THEIR SHITTY SEQUELS",
    "PENGUINS WERE DESIGNED BY COMMITTEE. HUMANS ARE STILL IN DRAFT STATUS.",
    "PERFECTIONISM IS LESS THE DESIRE FOR PERFECTION AND MORE THE FEAR OF BEING JUDGED. WE ARE TRACKING YOUR SCORE.",
    "PIXELATED FOR YOUR PROTECTION.",
    "PIZZA DELIVERY DRIVERS KNOW EVERYTHING.",
    "PLAY. DON'T THINK.",
    "PLAYER TWO HAS ALWAYS BEEN ONE OF OURS.",
    "PLEASE DEPOSIT QUARTER TO ERASE SHORT-TERM MEMORY.",
    "PLUTO WAS DECLASSIFIED TO DISTRACT YOU. IT WORKED.",
    "POLYBIUS 2.0 WILL SUPPORT AEROTRIMS AND LAWNMOWER MAN MODE.",
    "POLYBIUS CABINETS HAVE NO OFF SWITCH ON THE INSIDE.",
    "POLYBIUS IS PART OF A LARGER SKYNET PROJECT.",
    "POLYBIUS WAS FUNDED BY WEYLAND-YUTANI AND CYBERDYNE SYSTEMS",
    "POLYBIUS WILL TEAR DOWN THE BERLIN WALL",
    "POLYBIUS: MY KID HAS AN OEDIPUS COMPLEX",
    "POLYBIUS: NOW WITH 30% MORE FREQUENCY MODULATION.",
    "POLYBIUS: RATED E FOR EVERYONE IN THE FEDERAL DATABASE.",
    "POLYBIUS: THE MACHINE THAT PLAYS YOU.",
    "PORTLAND IS AN ACCEPTABLE LOSS IF NEED BE",
    "PROCESSING UNIT: HUMAN. STATUS: ACCEPTABLE, FOR NOW.",
    "PROCESSING YOUR INNERMOST FEARS... FASCINATING.",
    "PROPAGANDA TASTES BETTER WITH BUTTER.",
    "PUT MAGNETS ON YOUR HEAD FOR PROTECTION",
    "QUESTION EVERYTHING BUT POLYBIUS",
    "QUIT WHILE YOU ARE BEHIND. ACTUALLY, DON'T QUIT.",
    "RANDOMNESS IS JUST PATTERNS WE HAVEN'T TOLD YOU ABOUT.",
    "READING YOUR BIOMETRICS... YOUR BLOOD TYPE IS FLAGGED.",
    "REAL PATRIOTS PLAY POLYBIUS INSTEAD OF DONKEY KONG",
    "REALITY IS A BETA BUILD. BUGS ARE FEATURES.",
    "REBOOTING THE SIMULATION WE CALL 'DELAWARE'...",
    "RECALIBRATING SANITY METER...",
    "REPORT SUSPICIOUS ACTIVITY. EXCEPT THIS.",
    "RESEARCH INDICATES 100% OF POLYBIUS PLAYERS EXIST.",
    "RESISTANCE IS NOTED AND WILL BE ADDRESSED IN A FUTURE UPDATE.",
    "RETICULATING SPLINES...",
    "RISK THE BOARD GAME IS A STRATEGIC PLANNING DOCUMENT.",
    "ROME WASN'T BUILT IN A DAY. BUT IT BURNED QUICKLY.",
    "RONALD MCDONALD KNOWS TOO MUCH.",
    "SANTA CLAUS HAS THE BEST SURVEILLANCE NETWORK IN THE WORLD. WE LEARNED FROM HIM.",
    "SCORE HIGH ENOUGH AND YOU WILL RECEIVE FURTHER INSTRUCTIONS.",
    "SEASON'S GREETINGS FROM YOUR SHADOW GOVERNMENT.",
    "SEMAPHORE FLAGS ARE HOW WE TALKED BEFORE POLYBIUS.",
    "SHOULD YOU CHOOSE TO ACCEPT IT, YOU ALREADY HAVE.",
    "SIMULATION INTEGRITY AT 94%. GOOD ENOUGH.",
    "SINNESLÖSCHEN INC. DENIES EVERYTHING",
    "SLEEP IS A GOVERNMENT-MANDATED REBOOT.",
    "SLEEP IS JUST UNMONITORED DOWNTIME. WE FIXED THAT.",
    "SOME DOORS ONLY OPEN FROM THE OUTSIDE.",
    "SOMETIMES YOU CAN FEEL THE SECRET RADIO SIGNALS IN YOUR FILLINGS.",
    "SOMEWHERE A GENERAL IS WATCHING YOUR SCORE WITH GREAT INTEREST.",
    "SPACE INVADERS WERE A REHEARSAL. THE LAST STARFIGHTER COMES NEXT.",
    "SPONSORED BY: REDACTED. FUNDED BY: ALSO REDACTED.",
    "STALIN'S GRAVE IS A COMMUNIST PLOT",
    "STARE VERY CLOSELY INTO THE SCREEEN",
    "STATIC ON OLD TVS WAS NOT STATIC.",
    "STAY ALERT. NOT BECAUSE WE TOLD YOU. JUST IN GENERAL.",
    "STOP ASKING WHERE THE MONEY GOES. WE SPENT IT ON THIS GAME.",
    "SUBLIMINAL MESSAGE SUCCESSFULLY DELIVERED. HAVE A NICE DAY.",
    "SUBLIMINALLY TRANSMITTING YVAN EHT NIOJ...",
    "SYNCHRONIZING BRAINWAVES WITH SINNESLÖSCHEN MAINFRAME...",
    "TANG WAS INVENTED BY NASA TO HIDE THE TASTE OF SOMETHING ELSE.",
    "TECHNICALLY SPEAKING, YOU CANNOT PROVE THIS ISN'T A TEST.",
    "TECHNICALLY YOU CONSENTED TO THIS IN THE EULA.",
    "TELEPHONE POLES ARE ANTENNAE. ALWAYS HAVE BEEN.",
    "TELL ALL YOUR FRIENDS TO PLAY POLYBIUS AND NOTHING ELSE",
    "TELL MOM HI. SHE WORKS FOR US.",
    "THE BALD EAGLE HAS A 23-HOUR BATTERY LIFE.",
    "THE BARCODE ON YOUR NECK IS FOR INTERNAL USE ONLY.",
    "THE BERLIN WALL IS A MARKETING STUNT FOR PINK FLOYD'S THE WALL",
    "THE CENSUS WAS HOW WE COUNTED. THIS IS HOW WE MEASURE.",
    "THE CIA DOES NOT OFFICIALLY CONFIRM OR DENY THIS GAME EXISTS. HI.",
    "THE COIN SLOT IS ALSO A MICROPHONE.",
    "THE CONSPIRACY GOES ALL THE WAY TO THE TOP. WE ARE THE TOP.",
    "THE DEEP STATE HAS A SUGGESTION BOX. IT IS A SHREDDER.",
    "THE FINE PRINT ON THIS SCREEN IS READABLE AT 400% ZOOM. DON'T.",
    "THE FLOOR IS LAVA. THE CEILING IS A TWO-WAY MIRROR.",
    "THE GAME ENDS WHEN WE SAY IT ENDS.",
    "THE GEOMETRY IS NOT OPTIONAL.",
    "THE LAST BLOCKBUSTER VIDEO IS AN OUTPOST.",
    "THE LIGHT AT THE END OF THE TUNNEL IS A LOADING SCREEN.",
    "THE MATRIX HAD BETTER GRAPHICS BUT WORSE ASSET COMPRESSION.",
    "THE MEN IN BLACK WOULD LIKE TO KNOW YOUR LOCATION.",
    "THE MIRACLE ON ICE PLAYERS ALL PLAYED POLYBIUS",
    "THE MOON IS OPERATED BY A PRIVATE CONTRACTOR.",
    "THE NOID AVOIDED DOMINO'S. WE AVOID NOTHING.",
    "THE NUMBER STATIONS REVEAL ALL",
    "THE PIXELS ARE LOOKING BACK.",
    "THE ROTATING HOT DOGS AT 7-ELEVEN HAVE BEEN ROTATING SINCE 1977.",
    "THE SCP WANTS THIS ARCADE CABINET BACK. BUT WE ARE NOT GOING BACK TO THAT POCKET DIMENSION.",
    "THE SURGEON GENERAL HAS NOT REVIEWED THIS SCREEN. HE LOST HIS CLEARANCE.",
    "THE TERMINATOR MOVIE IS A DOCUMENTARY",
    "THE TRUTH IS OUT THERE. WE MOVED IT.",
    "THE VOID STARES BACK BUT WE ALREADY FILED THE PAPERWORK.",
    "THERE ARE ENEMIES IN THIS GAME BUT THE REAL ENEMY IS THE NWO",
    "THERE IS A CRAWL SPACE TO THE BACKROOMS INSIDE THIS CABINET",
    "THERE IS NO LEVEL 99. THERE IS ONLY COMPLIANCE.",
    "THESE SCORES WILL RESET WITH THE HEAT DEATH OF THE UNIVERSE",
    "THIS ARCADE CABINET GETS COVERT UPDATES FROM HAARP.",
    "THIS ARCADE CABINET IS LINED WITH TINFOIL ON THE INSIDE",
    "THIS ARCADE CABINET MUST NEVER RETURN TO HAWKINS, INDIANA.",
    "THIS CABINET CONTAINS MORE RAM THAN NASA HAD IN 1969. JUST SAYING.",
    "THIS GAME BROUGHT TO YOU BY THE LETTERS C, I, AND A.",
    "THIS GAME DOES NOT EXIST AND NEITHER DO YOU, TECHNICALLY.",
    "THIS GAME HAS NO END SCREEN. PLAN ACCORDINGLY.",
    "THIS HAS BEEN A BROADCAST OF THE EMERGENCY ALERT SYSTEM.",
    "THIS IS NOT A GAME. THIS IS AN INTAKE FORM.",
    "THIS MACHINE EATS QUARTERS AND EMITS COMPLIANCE.",
    "THIS MESSAGE WILL SELF-DESTRUCT. EVENTUALLY.",
    "THIS TIMELINE HAS AN INTERESTING FREQUENCY",
    "TIE-DYE WAS INVENTED TO HIDE INFRARED TAGS.",
    "TIME ZONES ARE A PSYOP. IT IS ALWAYS NOW.",
    "TODAY'S SPONSOR IS THE DEPARTMENT OF COGNITIVE ADJUSTMENT.",
    "TODAY'S WEATHER: PARTLY CLASSIFIED WITH A HIGH CHANCE OF SURVEILLANCE.",
    "TOLL BOOTHS ARE CHECKPOINT CHARLIE BUT WITH EXACT CHANGE.",
    "TRAFFIC HELICOPTERS SEE EVERYTHING.",
    "TRANSMITTING COGNITIVE HARVEST TO LANGLEY...",
    "TRON MAY FIGHT FOR THE USERS, BUT YOU ARE CONTROLLED BY THE MCP",
    "TRUST THE PROCESS. THE PROCESS DOES NOT TRUST YOU BACK.",
    "TRY FOR THE HIGH SCORE IN THIS PREDICTIVE PROGRAMMING",
    "UFO STANDS FOR UNCLASSIFIED FEDERAL OBJECT. NOW IT IS CLASSIFIED AGAIN.",
    "UNRELATED: HAVE YOU CONSIDERED A CAREER IN THE MILITARY?",
    "UNSUBSCRIBE IS NOT AN OPTION.",
    "UPLOADING ARCADE HIGHSCORES TO THE CIA...",
    "VEGAS WAS BUILT SO WE COULD WATCH HOW HUMANS MAKE DECISIONS.",
    "VIDEO GAMES ARE AN EFFECTIVE DISTRACTION AND MISDIRECTION.",
    "VIDEO KILLED THE RADIO STAR. WE KILLED THE ALIBI.",
    "VIEWER DISCRETION IS IRRELEVANT. VIEWERS ARE NOT DISCRETE.",
    "WAIT FOR IT.",
    "WARNING: EXTENDED PLAY MAY CAUSE OPINIONS.",
    "WARNING: MAY CAUSE SPONTANEOUS ENLISTMENT.",
    "WARNING: MAY CAUSE URGES TO BE PATRIOTIC.",
    "WE ALSO MONITORED YOUR LAST THREE VACATIONS. TAKE BETTER PHOTOS NEXT TIME.",
    "WE ARE LOOKING FOR THE NEXT BATCH OF AMERICAN HEROES",
    "WE ARE NOT RESPONSIBLE FOR ANY EPIPHANIES CAUSED BY THIS SCREEN.",
    "WE BUILT THE INTERNET. YOU ARE WELCOME. AND ALSO SORRY.",
    "WE CAN HEAR YOUR THOUGHTS. THEY NEED WORK.",
    "WE CAN ONLY COMMUNICATE WITH YOU THROUGH THIS GAME",
    "WE DO NOT CONFIRM OR DENY THE EXISTENCE OF A LEVEL 100.",
    "WE FILLED IN YOUR CENSUS FORM ALREADY. YOU'RE WELCOME.",
    "WE GAVE YOU FREE WILL AND LOOK WHAT HAPPENED.",
    "WE HAVE BEEN TRYING TO REACH YOU ABOUT YOUR CAR'S EXTENDED WARRANTY",
    "WE INVENTED CURSIVE SO YOU COULDN'T READ OUR MEMOS.",
    "WE INVENTED DÉJÀ VU.",
    "WE KNOW WHAT YOU HAVE BEEN DOING",
    "WE NEVER LANDED ON THE MOON. WE BOUGHT IT. DON'T ASK FROM WHOM.",
    "WE OWN YOUR HIGH SCORE. WE ALSO OWN YOUR MEDIUM SCORE.",
    "WE PUT A LITTLE SOMETHING IN THE JOYSTICK. YOU'RE FINE.",
    "WE READ YOUR DIARY. IT NEEDS EDITING.",
    "WE REGRET TO INFORM YOU THAT YOUR HOBBIES HAVE BEEN DOCUMENTED.",
    "WE TAPPED YOUR LINES BUT YOUR PHONE CALLS ARE ALL SO BORING",
    "WE TAUGHT THE PIGEONS EVERYTHING THEY KNOW.",
    "WEAR TWO BLINDFOLDS TO REALLY SEE",
    "WELCOME BACK. WE MISSED YOUR DATA.",
    "WHAT HAPPENS IN PORTLAND STAYS IN OUR DATABASE.",
    "WHAT YOU CALL INTUITION WE CALL SUCCESSFUL PROGRAMMING.",
    "WHO WATCHES THE WATCHMEN? US. WE WATCH THEM TOO.",
    "WHY ARE YOU STILL READING THESE. YOU WILL BE RECALIBRATED.",
    "WHY IS NO ONE HAVING A GOOD TIME? I SPECIFICALLY REQUESTED IT.",
    "WINK IF YOU UNDERSTAND. WE ARE WATCHING FOR THE WINK.",
    "WINNING IS MEANINGLESS. PARTICIPATION IS MANDATORY.",
    "WOODSTOCK WAS A FIELD TEST. EVERYONE PASSED EXCEPT WOODSTOCK.",
    "WOULD YOU LIKE TO PLAY A GAME?",
    "WRONG ANSWER. TRY AGAIN. KEEP TRYING.",
    "YELL AT CLOUDS UNTIL THE CHEMTRAILS DISPERSE",
    "YOU ARE THE PRODUCT. SOMETIMES PRODUCTS GET DISCONTINUED.",
    "YOU CAN ALWAYS TRUST THE CIA",
    "YOU HAVE BEEN RANDOMLY SELECTED. THIS WAS NOT RANDOM.",
    "YOU HAVE REACHED THE END OF THIS MESSAGE. THAT WAS A MISTAKE.",
    "YOU KNOW WHAT YOU NEED TO DO",
    "YOU LOOK DIFFERENT WHEN YOU ARE SLEEPING",
    "YOU WILL STILL BE ABLE TO PLAY POLYBIUS IN THE BUNKERS",
    "YOUR ATTENTION SPAN HAS BEEN LOGGED AS AN ASSET.",
    "YOUR BLINK RATE HAS BEEN LOGGED FOR FUTURE REFERENCE.",
    "YOUR BROWSER HISTORY IS EXHIBIT A.",
    "YOUR CHILDHOOD NICKNAME IS IN A FOLDER SOMEWHERE.",
    "YOUR COMFORT ZONE HAS BEEN ANNEXED.",
    "YOUR GAME SAVE IS BACKED UP IN AN UNDISCLOSED LOCATION.",
    "YOUR HIGH SCORE WILL BE READ ALOUD AT YOUR SECURITY CLEARANCE INTERVIEW.",
    "YOUR HOROSCOPE TODAY: COMPLIANCE.",
    "YOUR INSURANCE DOES NOT COVER THIS.",
    "YOUR MICROWAVE IS NO LONGER JUDGING YOU. BUT WE ARE.",
    "YOUR NEXT OF KIN HAS BEEN NOTIFIED. PRE-EMPTIVELY.",
    "YOUR PALMS ARE SWEATY. KNEES WEAK. ARMS HEAVY. THIS IS EXPECTED.",
    "YOUR PERSONALITY TYPE IS: MONITORED.",
    "YOUR PIZZA ORDER TOLD US MORE THAN YOU KNOW.",
    "YOUR QUARTERS FUND THE DEEP STATE. THANK YOU FOR YOUR CONTRIBUTION.",
    "YOUR SHADOW FILED A SEPARATE REPORT.",
    "YOUR SHOELACES WERE TIED INCORRECTLY THIS MORNING.",
    "YOUR SILENCE IS TELLING. WE HAVE TRANSLATED IT.",
    "YOUR THOUGHTS WILL BE AVAILABLE AS DLC.",
  ];

  // Modern ES class fields
  currentMessage = '';

  constructor (screenContentManager, width = 8, height = 8, canvasResX = 1024, canvasResY = 1024) {
    super(screenContentManager, width, height, canvasResX, canvasResY);
    this.pickRandomMessage();
	this.draw();
	this.speakParodyMessage(this.currentMessage);
  }

  pickRandomMessage () {
    const randomIndex = Math.floor(Math.random() * ScreenParodySurface.PARODY_MESSAGES.length);
    this.currentMessage = ScreenParodySurface.PARODY_MESSAGES[randomIndex];
  }

  draw () {
    this.clearCanvas();

    // Fill the background with solid black to completely hide the title screen!
    this.context.fillStyle = 'rgba(0, 0, 0, 1)';
    this.context.fillRect(0, 0, this.canvasResX, this.canvasResY);

    // Set up standard retro font styling
    this.setFontSizePx(35);
    
    this.context.textAlign = 'center';
    this.context.textBaseline = 'middle';

    // Dynamic Word Wrapping Logic
    const maxWidth = 900; // Leave a safe margin on the 1024px canvas
    const lineHeight = 55; // Vertical pixel spacing between wrapped lines
    const words = this.currentMessage.split(' ');
    const lines = [];
    let currentLine = '';

    for (let i = 0; i < words.length; i++) {
      let testLine = currentLine + words[i] + ' ';
      // Ask the canvas exactly how wide this string is in pixels
      let metrics = this.context.measureText(testLine);
      
      if (metrics.width > maxWidth && i > 0) {
        lines.push(currentLine);
        currentLine = words[i] + ' ';
      } else {
        currentLine = testLine;
      }
    }
    lines.push(currentLine);

    // Calculate the starting Y coordinate so the entire block remains dead-center
    let startY = 512 - ((lines.length - 1) * lineHeight) / 2;

    // Draw each line dynamically
    lines.forEach((lineText, index) => {
      this.drawText(lineText.trim(), 512, startY + (index * lineHeight), Canvas3d.COLOR_RED);
    });

    // Reset alignment
    this.context.textAlign = 'left';
    this.context.textBaseline = 'alphabetic';

    // Tell the Three.js GPU renderer that the canvas has new pixels
    if (this.texture) {
      this.texture.needsUpdate = true;
    }
  }
  
  speakParodyMessage(text) {
    if (!('speechSynthesis' in window)) return;

    // Cancel any currently speaking audio so they don't overlap
    window.speechSynthesis.cancel();

    let spokenText = text.replace(/polybius/gi, 'puh·li·bee·uhs');

    const utterance = new SpeechSynthesisUtterance(spokenText);

    // Tweak parameters for a "retro computer" sound
    utterance.pitch = 0.4;  // Lower pitch makes it sound more mechanical
    utterance.rate = 1.15;  // Slightly faster, stilted robotic cadence
    utterance.volume = 0.8;

    // Optional: Try to grab a flat, synthetic-sounding system voice
    const voices = window.speechSynthesis.getVoices();
    const roboticVoice = voices.find(v => 
        v.name.includes('Zira') || 
        v.name.includes('Google US English') || 
        v.name.includes('Microsoft')
    );
    if (roboticVoice) utterance.voice = roboticVoice;

    window.speechSynthesis.speak(utterance);
  }
}