import Canvas3d from '@/Object/Screen/Canvas3d';

export default class ScreenParodySurface extends Canvas3d {
  static PARODY_MESSAGES = [
	"HACK THE GIBSON. HACK THE PLANET.",
    "A MAN IN A BLACK SUIT WILL BE WITH YOU SHORTLY.",
    "A POLYBIUS MACHINE IS IN EVERY DENTIST'S OFFICE. THINK ABOUT IT.",
    "AGENT ORANGE BUILDS STRONG BONES FOR A HEALTHY TOMORROW!",
    "ALL YOUR SUBCONSCIOUS ARE BELONG TO US.",
    "AMNESIA MODE ENGANGAGED",
    "ARE YOU WINNING, SON? (PLEASE RESPOND IN BINARY)",
    "ATARI DID NOT GO BANKRUPT. THEY WENT UNDERGROUND.",
    "BE SEEING YOU. ESPECIALLY WHEN YOU ARE SLEEPING.",
    "BIGFOOT, WE KNOW YOU LIVE IN PORTLAND",
    "BLINK TWICE IF YOU NEED HELP. TOO LATE.",
    "BOB HOPE WORKED FOR US. SO DID BOB BARKER. ALL BOBS DO.",
    "CALIBRATING PSYCHOACTIVE STROBE FREQUENCIES...",
    "CHEMTRAILS ARE JUST POLYBIUS LOADING SCREENS FOR THE SKY.",
    "COMPLY WITH THE MEN IN BLACK",
    "COMPUTERS WON'T REPLACE HUMANS. YET.",
    "CONGRATULATIONS. YOUR SCORES HAVE BEEN FORWARDED TO YOUR DRAFT BOARD.",
    "DELEWARE IS NOT REAL.",
    "DID YOU KNOW PONG WAS A PSYOP? THIS IS WORSE.",
    "DISCLAIMER: SIDE EFFECTS MAY INCLUDE PATRIOTISM.",
    "DO NOT DISCUSS THIS GAME WITH YOUR THERAPIST. WE ALREADY GOT TO THEM.",
    "DO NOT LOOK DIRECTLY AT THE POLYGONS.",
    "DON'T WORRY. YOU WON'T REMEMBER",
    "ERROR: MK-ULTRA DRIVER NOT FOUND. FALLING BACK TO HYPNOTISM.",
    "EVERY QUARTER YOU INSERT IS A VOTE FOR THE NEW WORLD ORDER.",
    "EVERY TIME YOU DIE IN THIS GAME A PIGEON IS REPLACED.",
    "EXTRACTING DREAD. PLEASE WAIT...",
    "FLUORIDE IS HOW WE UPDATE YOUR FIRMWARE.",
    "FONZIE JUMPING THE SHARK WAS A BROADCAST TEST. IT WORKED.",
    "FOR SECURITY REASONS PLEASE FORGET YOUR OWN NAME.",
    "FRANK SINATRA WAS OUR BEST FIELD AGENT.",
    "FURBIES WERE LISTENING. THEY STILL ARE.",
    "GAME DIFFICULTY IS CALIBRATED TO YOUR CHILDHOOD TRAUMA.",
    "HAVE YOU CONSIDERED THAT YOUR REFLECTION MAY HAVE DIFFERENT OPINIONS?",
    "HIGH SCORES ARE USED TO DETERMINE WHO GETS THEIR OWN WEATHER.",
    "IF EYES ARE THE WINDOWS TO THE SOUL, THIS SCREEN IS THE DOOR.",
    "IF YOU FEEL WATCHED, THAT IS BECAUSE YOU ARE DOING GREAT.",
    "IF YOU REMEMBER PLAYING THIS GAME, YOU WEREN'T SUPPOSED TO.",
    "IF YOU SMELL BURNING TOAST, YOU ARE GETTING THE HIGH SCORE.",
    "IF YOU START TO FEEL SICK, THE AGENTS WILL BE HERE SHORTLY",
    "IGNORANCE IS BLISS. POLYBIUS IS IGNORANCE.",
    "IN CASE OF NUCLEAR EMERGENCY, KEEP PLAYING.",
    "IN THE FUTURE POLYBIUS WILL MINE DOGECOIN",
    "JOYSTICK DATA IS STORED IN A MOUNTAIN IN UTAH.",
    "JUST ONE MORE QUARTER. JUST ONE MORE. JUST.",
    "KIDS, REPORT YOUR PARENTS IF THEY ARE COMMIES",
    "KIDS, UNCLE RONNIE REAGAN LOVES YOU!",
    "KNOWING IS HALF THE BATTLE. WE OWN THE OTHER HALF.",
    "LEGALLY THIS IS A WELLNESS DEVICE.",
    "LOADING YOUR REPLACEMENT. PLEASE STAND BY.",
    "MANIFESTING YOUR COOPERATION. IT IS WORKING.",
    "MIRRORS ARE PARALLEL UNIVERSES LOOKING BACK ON US",
    "MK-ULTRA IS PART OF THIS BALANCED BREAKFAST",
	"MOZART'S GHOST IS THE HOTTEST BAND ON THE NET",
    "MR. T PITIES THE FOOL WHO STOPS PLAYING.",
    "NASA HAS A POLYBIUS MACHINE ON THE SPACE STATION. FOR MORALE.",
    "NEXT TIME WE'LL PLAY GLOBAL THERMONUCLEAR WAR",
    "NO ONE WINS. SOME PEOPLE JUST LOSE MORE SLOWLY.",
    "NOT RESPONSIBLE FOR ANY UFOS YOU MAY NOW BE ABLE TO SEE.",
    "NOW ENTERING: THE COMPLIANT ZONE.",
    "ORWELL SAID 1984 WAS A WARNING. WE TOOK IT AS A CHECKLIST.",
    "OUR LEGAL TEAM CONSIDERS THIS SCREEN A TERMS OF SERVICE AGREEMENT.",
    "PAY NO ATTENTION TO THE MEN IN BLACK, NOR THEIR SHITTY SEQUELS",
    "PIXELATED FOR YOUR PROTECTION.",
    "PLAY. DON'T THINK.",
    "PLAYER TWO HAS ALWAYS BEEN ONE OF OURS.",
    "PLEASE DEPOSIT QUARTER TO ERASE SHORT-TERM MEMORY.",
    "POLYBIUS CABINETS HAVE NO OFF SWITCH ON THE INSIDE.",
    "POLYBIUS WILL TEAR DOWN THE BERLIN WALL",
    "POLYBIUS: MY KID HAS AN OEDIPUS COMPLEX",
    "POLYBIUS: RATED E FOR EVERYONE IN THE FEDERAL DATABASE.",
    "PORTLAND IS AN ACCEPTABLE LOSS IF NEED BE",
    "PROCESSING YOUR INNERMOST FEARS... FASCINATING.",
    "PUT MAGNETS ON YOUR HEAD FOR PROTECTION",
    "QUESTION EVERYTHING BUT POLYBIUS",
    "READING YOUR BIOMETRICS... YOUR BLOOD TYPE IS FLAGGED.",
    "REAL PATRIOTS PLAY POLYBIUS INSTEAD OF DONKEY KONG",
    "REBOOTING THE SIMULATION WE CALL 'DELAWARE'...",
    "RECALIBRATING SANITY METER...",
    "RESEARCH INDICATES 100% OF POLYBIUS PLAYERS EXIST.",
    "RETICULATING SPLINES...",
    "RONALD MCDONALD KNOWS TOO MUCH.",
    "SHOULD YOU CHOOSE TO ACCEPT IT, YOU ALREADY HAVE.",
    "SINNESLÖSCHEN INC. DENIES EVERYTHING",
    "SLEEP IS JUST UNMONITORED DOWNTIME. WE FIXED THAT.",
    "STALIN'S GRAVE IS A COMMUNIST PLOT",
    "STARE VERY CLOSELY INTO THE SCREEEN",
    "SUBLIMINAL MESSAGE SUCCESSFULLY DELIVERED. HAVE A NICE DAY.",
    "SUBLIMINALLY TRANSMITTING YVAN EHT NIOJ...",
    "SYNCHRONIZING BRAINWAVES WITH SINNESLÖSCHEN MAINFRAME...",
    "TECHNICALLY YOU CONSENTED TO THIS IN THE EULA.",
    "TELL ALL YOUR FRINEDS TO PLAY POLYBIUS AND NOTHING ELSE",
    "THE BERLIN WALL IS A MARKETING STUNT FOR PINK FLOYD'S THE WALL",
    "THE CIA DOES NOT OFFICIALLY CONFIRM OR DENY THIS GAME EXISTS. HI.",
    "THE COIN SLOT IS ALSO A MICROPHONE.",
    "THE GAME ENDS WHEN WE SAY IT ENDS.",
    "THE GEOMETRY IS NOT OPTIONAL.",
    "THE MATRIX HAD BETTER GRAPHICS BUT WORSE ASSET COMPRESSION.",
    "THE MEN IN BLACK WOULD LIKE TO KNOW YOUR LOCATION.",
    "THE MIRACLE ON ICE PLAYERS ALL PLAYED POLYBIUS",
    "THE MOON IS OPERATED BY A PRIVATE CONTRACTOR.",
    "THE NUMBER STATIONS REVEAL ALL",
    "THE PIXELS ARE LOOKING BACK.",
    "THE SURGEON GENERAL HAS NOT REVIEWED THIS SCREEN. HE LOST HIS CLEARANCE.",
    "THE TERMINATOR MOVIE IS A DOCUMENTARY",
    "THERE ARE ENEMIES IN THIS GAME BUT THE REAL ENEMY IS THE NWO",
    "THERE IS NO LEVEL 99. THERE IS ONLY COMPLIANCE.",
    "THIS ARCADE CABINET IS LINED WITH TINFOIL ON THE INSIDE",
    "THIS CABINET CONTAINS MORE RAM THAN NASA HAD IN 1969. JUST SAYING.",
    "THIS GAME BROUGHT TO YOU BY THE LETTERS C, I, AND A.",
    "THIS GAME DOES NOT EXIST AND NEITHER DO YOU, TECHNICALLY.",
    "THIS IS NOT A GAME. THIS IS AN INTAKE FORM.",
    "THIS TIMELINE HAS AN INTERESTING FREQUENCY",
    "TIME ZONES ARE A PSYOP. IT IS ALWAYS NOW.",
    "TODAY'S SPONSOR IS THE DEPARTMENT OF COGNITIVE ADJUSTMENT.",
    "TRANSMITTING COGNITIVE HARVEST TO LANGLEY...",
    "TRY FOR THE HIGH SCORE IN THIS PREDICTIVE PROGRAMMING",
    "TWO TRUTHS AND A LIE: POLYBIUS IS REAL. THE LIE IS YOURS TO FIND.",
    "UNRELATED: HAVE YOU CONSIDERED A CAREER IN THE MILITARY?",
    "UPLOADING ARCADE HIGHSCORES TO THE CIA...",
    "WARNING: MAY CAUSE SPONTANEOUS ENLISTMENT.",
    "WARNING: MAY CAUSE URGES TO BE PATRIOTIC.",
    "WE ARE LOOKING FOR THE NEXT BATCH OF AMERICAN HEROES",
    "WE CAN ONLY COMMUNICATE WITH YOU THROUGH THIS GAME",
    "WE HAVE BEEN TRYING TO REACH YOU ABOUT YOUR CAR'S EXTENDED WARRANTY",
    "WE KNOW WHAT YOU HAVE BEEN DOING",
    "WE PUT A LITTLE SOMETHING IN THE JOYSTICK. YOU'RE FINE.",
    "WE REGRET TO INFORM YOU THAT YOUR HOBBIES HAVE BEEN DOCUMENTED.",
    "WE TAPPED YOUR LINES BUT YOUR PHONE CALLS ARE ALL SO BORING",
    "WEAR TWO BLINDFOLDS TO REALLY SEE",
    "WINNING IS MEANINGLESS. PARTICIPATION IS MANDATORY.",
    "WOULD YOU LIKE TO PLAY A GAME?",
    "YELL AT CLOUDS UNTIL THE CHEMTRAILS DISPERSE",
    "YOU CAN ALWAYS TRUST THE CIA",
    "YOU KNOW WHAT YOU NEED TO DO",
    "YOU LOOK DIFFERENT WHEN YOU ARE SLEEPING",
    "YOU WILL STILL BE ABLE TO PLAY POLYBIUS IN THE BUNKERS",
    "YOUR BLINK RATE HAS BEEN LOGGED FOR FUTURE REFERENCE.",
    "YOUR GAME SAVE IS BACKED UP IN AN UNDISCLOSED LOCATION.",
    "YOUR HIGH SCORE WILL BE READ ALOUD AT YOUR SECURITY CLEARANCE INTERVIEW.",
    "YOUR INSURANCE DOES NOT COVER THIS.",
    "YOUR NEXT OF KIN HAS BEEN NOTIFIED. PRE-EMPTIVELY.",
    "YOUR PALMS ARE SWEATY. KNEES WEAK. ARMS HEAVY. THIS IS EXPECTED.",
    "YOUR QUARTERS FUND THE DEEP STATE. THANK YOU FOR YOUR CONTRIBUTION.",
  ];

  // Modern ES class fields
  currentMessage = '';

  constructor (screenContentManager, width = 8, height = 8, canvasResX = 1024, canvasResY = 1024) {
    super(screenContentManager, width, height, canvasResX, canvasResY);
    this.pickRandomMessage();
	this.draw();
  }

  pickRandomMessage () {
    const randomIndex = Math.floor(Math.random() * ScreenParodySurface.PARODY_MESSAGES.length);
    this.currentMessage = ScreenParodySurface.PARODY_MESSAGES[randomIndex];
  }

  draw () {
    this.clearCanvas();

    // Fill the background with solid black to completely hide the title screen!
    this.context.fillStyle = 'rgba(0, 0, 0, 1)';
    this.context.fillRect(0, 0, this.canvasResX, this.canvasResY);

    // Set up standard retro font styling
    this.setFontSizePx(35);
    
    this.context.textAlign = 'center';
    this.context.textBaseline = 'middle';

    // Dynamic Word Wrapping Logic
    const maxWidth = 900; // Leave a safe margin on the 1024px canvas
    const lineHeight = 55; // Vertical pixel spacing between wrapped lines
    const words = this.currentMessage.split(' ');
    const lines = [];
    let currentLine = '';

    for (let i = 0; i < words.length; i++) {
      let testLine = currentLine + words[i] + ' ';
      // Ask the canvas exactly how wide this string is in pixels
      let metrics = this.context.measureText(testLine);
      
      if (metrics.width > maxWidth && i > 0) {
        lines.push(currentLine);
        currentLine = words[i] + ' ';
      } else {
        currentLine = testLine;
      }
    }
    lines.push(currentLine);

    // Calculate the starting Y coordinate so the entire block remains dead-center
    let startY = 512 - ((lines.length - 1) * lineHeight) / 2;

    // Draw each line dynamically
    lines.forEach((lineText, index) => {
      this.drawText(lineText.trim(), 512, startY + (index * lineHeight), Canvas3d.COLOR_RED);
    });

    // Reset alignment
    this.context.textAlign = 'left';
    this.context.textBaseline = 'alphabetic';

    // Tell the Three.js GPU renderer that the canvas has new pixels
    if (this.texture) {
      this.texture.needsUpdate = true;
    }
  }
}